export const TRIP_LIST_REQUEST = 'TRIP_LIST_REQUEST'
export const TRIP_LIST_SUCCESS = 'TRIP_LIST_SUCCESS'
export const TRIP_LIST_FAIL = 'TRIP_LIST_FAIL'


export const TRIP_DETAILS_REQUEST = 'TRIP_DETAILS_REQUEST'
export const TRIP_DETAILS_SUCCESS = 'TRIP_DETAILS_SUCCESS'
export const TRIP_DETAILS_FAIL = 'TRIP_DETAILS_FAIL'


export const SELECT_TRIP_FOR_BOOKING = 'SELECT_TRIP_FOR_BOOKING'
export const CANCEL_TRIP_FOR_BOOKING = 'CANCEL_TRIP_FOR_BOOKING'

export const SAVE_BOOKING_INFO = 'SAVE_BOOKING_INFO'
export const SAVE_PAYMENT_METHOD = 'SAVE_PAYMENT_METHOD'


